"""add Custom

Revision ID: 89de5c0c5b9c
Revises: 86f7ec9f3266
Create Date: 2024-06-24 06:35:38.020042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '89de5c0c5b9c'
down_revision: Union[str, None] = '86f7ec9f3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Custom',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'description', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column('price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Custom')
    # ### end Alembic commands ###
