"""initial

Revision ID: bf228ce01e37
Revises:
Create Date: 2024-06-24 03:24:18.522400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bf228ce01e37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Artists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            'full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column('band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'Blog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'content', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            'created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            'image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            'file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'Role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'User',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['Role.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Blog')
    op.drop_table('Artists')
    # ### end Alembic commands ###
